### ISSUE TITLE
Upate or latest release

### ISSUE THREAD

**Issue by brightinnovator** [idealist1508/Recoll-Full-Text-Search-For-Calibre#2]
Any update or latest release can be done?

**Comment by idealist1508** [comment]
Try this https://github.com/idealist1508/Recoll-Full-Text-Search-For-Calibre/blob/master/Recoll%20Full%20Text%20Search.zip

**Comment by brightinnovator** [comment]
The plugin is not visible

Downloaded: https://www.fosshub.com/Calibre.html?dwl=calibre-portable-installer-5.14.0.exe
Downloaded the above plugin and followed the steps..However it is not working

Can you please attach few screenshots of installation and icon and how does it works?

Note: i tried preferences - plugins - load plugin from file but still not working

A detailed steps with screenshots in the read me would benefit many

**Comment by idealist1508** [comment]
Can you see this plugin under preferences plugins?
![image](https://user-images.githubusercontent.com/4608274/114664877-a2166380-9cfc-11eb-80ff-f86f54fb3a5c.png)
If you can see it, than you can double click it to see settings.
![image](https://user-images.githubusercontent.com/4608274/114665040-cf631180-9cfc-11eb-8dc8-8ef26d7a9121.png)
 
Here is an icon in toolbar 
![image](https://user-images.githubusercontent.com/4608274/114664230-af7f1e00-9cfb-11eb-8d24-d265e68f6137.png)
You may need to activate it first under preferences toolbars
![image](https://user-images.githubusercontent.com/4608274/114665188-00434680-9cfd-11eb-8318-20bc8baf4909.png)

**Comment by goodev2021** [comment]
i saw the picture..but not sure what is the path in windows...

i don't see Calibre Library in home directory...neither .config

**Comment by goodev2021** [comment]
when i click a make a new recoll database..a black window open and closed immediately..looks there is some issue...

where i can find the old version or working version for windows of this recoll plugin

**Comment by idealist1508** [comment]
- You can find  path to Calibre Library in Calibre under
![grafik](https://user-images.githubusercontent.com/4608274/115074890-97c1b880-9efa-11eb-9fe3-7390f6799422.png)

- Path to Calibre config on windows is %appdata%\calibre\. Please see Install section in readme.md

- Black window should be a command prompt. You can check a calls with [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon#download).  and test it manually in command prompt.

- The previous source for Windows is [here]( https://github.com/idealist1508/Recoll-Full-Text-Search-For-Calibre/tree/0bcdf83a8b8233d3156209c7db03871fd144e258), but i think this version should also work under windows, you only need to config it properly.

**Comment by goodev2021** [comment]
I'm unable to find using procman as the black window closed immediately. also the old version throws the error - 

calibre, version 5.15.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'D:\\Recoll-Full-Text-Search-For-Calibre-0bcdf83a8b8233d3156209c7db03871fd144e258.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.15  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 319, in add_plugin
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'D:\\Recoll-Full-Text-Search-For-Calibre-0bcdf83a8b8233d3156209c7db03871fd144e258.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by goodev2021** [comment]
if possible, can you please fix it for windows and attached the plugin as zip file for the newer version

**Comment by idealist1508** [comment]
you should start procmon bevor click on a make a new recoll database. Procmon logs all calls to windows. you should look at some call with recollindex.exe in a path.

Old version works only with python 2 and old python. 

Current Version should work on Windows. Can you call recollindex.exe from command prompt?

**Comment by goodev2021** [comment]
not sure..for whatsoever reason it doesn't work in windows 10 and no errors. command prompt closed quickly

**Comment by idealist1508** [comment]
try to log commands with a procmon.
